data:
  raw_dir: data/raw
  flows_dir: data/flows
artifacts_dir: data/artifacts
models_dir: models
preprocess:
  feature_mode: 'intersection'
  chunk_size: 200000
training:
  batch_size: 128
  epochs: 10
  lr: 0.001
  weight_decay: 0.00001
  seed: 42
model:
  primary_caps: 32
  primary_dim: 8
  routing_iters: 3
  lstm_hidden: 128
  lstm_layers: 1
  dropout: 0.3